// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220323052319_datetime_dt_change")]
    partial class datetime_dt_change
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.AppointmentInfo", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AptDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AptTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            AptDate = new DateTime(2022, 3, 22, 23, 23, 18, 856, DateTimeKind.Local).AddTicks(8920),
                            AptTime = 20,
                            Email = "randomEmail@gmail.com",
                            GroupName = "A Group",
                            Phone = "555-555-5555",
                            Size = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
